default: &default
  host: localhost
  user: postgres
  password: ''
  adapter: postgres

development:
  <<: *default
  db: heroku_kemal_jennifer_development

test:
  <<: *default
  db: heroku_kemal_jennifer_test

production:
  <<: *default
  db: heroku_kemal_jennifer_production
